### ISSUE TITLE
Evaluate python parsing libraries

### ISSUE THREAD

**Issue by wshayes** [belbio/bel.py#1]
Goal is to use a parsing library that uses a standard EBNF formatted file to create the parser.

Options to investigate are Lark, Grako (now Tatsu) and Parsimonious.

**Comment by davidchen** [comment]
Tatsu was chosen for several reasons:

- Both @wshayes and I felt that this library was easier to use and navigate for the purposes of our parser
- Tatsu has evidently more support and open source contributions when compared to Lark (that is not necessarily to say it's better, but that we can reach out to comparatively more people working on this project in case we encounter any unexpected behavior)
- Tatsu's documentation is far more detailed than Lark's
- Tatsu supports semantic actions within the AST
- Tatsu can act as both a library and a command within a CLI (I believe Lark only supports the former)
