### ISSUE TITLE
Transform AST back into BEL

### ISSUE THREAD

**Issue by wshayes** [belbio/bel.py#14]
Input: AST

Return: {"subject": <subject>, "relationship": <relationship>, "object": <object>}

Given BEL AST, recreate the BEL Statement and return a dictionary of the subject, relationship, and object (don't include relationship and object if they are null).

**Comment by davidchen** [comment]
could be a method call in our library -- something like bel.flatten(AST) or bel.astdict(AST)

**Comment by davidchen** [comment]
should include version number as well

**Comment by davidchen** [comment]
issue resolved with addition of these 3 methods in BEL package:

-flatten()
-stmt_components()
-ast_components()
