### ISSUE TITLE
Begin detailed documentation for each of the current belpy functions

### ISSUE THREAD

**Issue by davidchen** [belbio/bel.py#19]
Need to specify required and optional parameters along with return values and types of each of these:

- parse
- stmt_components
- ast_components
- create
- flatten
- load
- validate
- suggest

**Comment by davidchen** [comment]
``def parse(statement: str, version:str='2.0.0', strict:bool=False):
    """Parses a BEL statement given as a string and returns a ParseObject, which contains an abstract syntax tree (AST) if the statement is valid. Else, the AST attribute is None and there will be exception messages in ParseObject.error and
    ParseObject.visual_err.

    Args:
        statement (str): statement to be parsed
        version (str): language version; defaults to 2.0.0
        strict (bool): specify to use strict or loose parsing; defaults to loose

    Returns:
        ParseObject: The ParseObject which contain either an AST or error messages

    """
`

**Comment by davidchen** [comment]
def parse(statement: str, version:str='2.0.0', strict:bool=False):
    """Parses a BEL statement given as a string and returns a ParseObject, which contains an abstract syntax tree (AST) if the statement is valid. Else, the AST attribute is None and there will be exception messages in ParseObject.error and
    ParseObject.visual_err.

    Args:
        statement (str): statement to be parsed
        version (str): language version; defaults to 2.0.0
        strict (bool): specify to use strict or loose parsing; defaults to loose

    Returns:
        ParseObject: The ParseObject which contain either an AST or error messages

    """

**Comment by wshayes** [comment]
The default version should be a configuration option.  I like to use Config.py (a python file for my Config), one approach is in the bel_api repo in the api directory.  Note that the customizable file should not be in the repo - a copy of it should be made with a .example or .sample that is stored in the repo.

**Comment by davidchen** [comment]
Finished documentation under https://github.com/wshayes/testbelparsing/commit/a0f5d3bbf74c79c7b01be9eec6a9b28c87a7b17d.

Opening another issue pertaining to the configuration option approach that William pointed out.
